### PR TITLE
Fix InChI on Windows

### PR DESCRIPTION
**Pull request by fredrikw**
These changes fixes InChI support on Windows builds for conda.

The first change was needed to make AppVeyour builds work again, the second makes the tests fail if output is not what's expected and the third actually fixes the issue.

### CODE REVIEW

**Comment by fredrikw** [comment]
It looks like the CI failures are all due to missing ENV variable ANACONDA_TOKEN. I suppose that would go away when merged?

**Comment by fredrikw** [comment]
Just wondered if anyone has seen this. I know that there's work on v3 but I still think that it would facilitate a lot if inchi was working on windows builds of this recipe.

**Comment by fredrikw** [comment]
If anyone else is interested in these builds, you can go to the CI builds and download the artifacts (at least for a couple of months more until they are deleted) and install with `conda install c:\path\to\your\downloaded\wheel\openbabelXXXXX.tar.bz2`

**Comment by mwojcikowski** [comment]
Sorry, for this prolonged silence, I somehow missed an initial email for that PR. As OpenBabel packages are built by CI, we need to figure out the build failures (uploads in fact).

**Comment by fredrikw** [comment]
If I understand correctly, PRs from different accounts don't have access to secure environmental variables so the build/upload failures _should_ fix themselves when you merge.

**Comment by mwojcikowski** [comment]
Indeed. I need to disable the uploads on PR's, so that they do not fail. Thank you for fixing InCHI on Windows!

**Pull request merged**
